---
name: Power Generation of Each Generating Unit

on:
  schedule:
    - cron: '10 * * * *'
  workflow_dispatch:

jobs:
  scrape-power-info:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-firefox:4.4
        ports:
          - 4444:4444
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python packages
        run: make python-ci
      - name: Run scraper
        run: python3 power_generation_of_each_generating_unit.py
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          author_email: tom4996131207@gmail.com
          author_name: huang06
          branch: 'main'
          github_token: ${{ secrets.GITHUB_TOKEN }}
