---
name: Power Supply for the Next Seven Days

on:
  schedule:
    - cron: '0 0,12 * * *'
  workflow_dispatch:

jobs:
  scrape-power-info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Launch Selenium hub
        run: docker run -d -p 4444:4444 --shm-size="2g" docker.io/selenium/standalone-firefox:4.4.0
      - name: Install Python packages
        run: |
          python3 -m pip install pipenv
          pipenv sync --system
      - name: Run scraper
        run: python3 power_supply_for_the_next_seven_days.py
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          author_email: tom4996131207@gmail.com
          author_name: huang06
          branch: 'main'
          github_token: ${{ secrets.GITHUB_TOKEN }}
